### ISSUE TITLE
Cmake报错

### ISSUE THREAD

**Issue by dmkr001** [shuttworth/E-LVI-SAM#1]
您好，
在您最新的提交里，CmakeLists.txt 文件里增加了下面的部分，但是使用文件里提供的docker环境直接进行编译时会出现报错，请问是需要安装额外的依赖库吗？
add_service_files(
  DIRECTORY srv
  FILES
  save_map.srv
)
![image](https://github.com/shuttworth/E-LVI-SAM/assets/32437323/8a326227-8f58-40cf-a8f6-7eb4edc5a995)

**Comment by shuttworth** [comment]
很感谢发现并反馈这个问题。在之前的commit中，确实引入了一些问题，现在通过最新的commit提交已经解决了，commit id = e6fe35345b67e796240a7cc25c4ff3a13a457a1b。最新代码在docker内cmake是通过的

![image](https://github.com/shuttworth/E-LVI-SAM/assets/46838923/c992db54-9ada-44ce-bc25-616fdd7ae753)

**Comment by dmkr001** [comment]
感谢您的回复与修复，已能正常编译使用。
